name: Publish Docker
on:
  push:
    branches: [master]

jobs:
  build:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to registry
      uses: elgonr/Publish-Docker-Github-Action@master
      with:
        registry: docker.pkg.github.com
        name: docker.pkg.github.com/EugenyEmelin/nest-rest-api/nest-rating-api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "develop"
